# Generated by Django 5.2.6 on 2025-09-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
